# Configuration Netlify pour Kodeks

[build]
  publish = "dist"
  command = "npm run build"

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.googleapis.com https://apis.google.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https: http:;
      font-src 'self' data:;
      connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://firestore.googleapis.com https://covers.openlibrary.org https://openlibrary.org wss://*.firebaseio.com;
      frame-src 'self' https://*.firebaseapp.com https://accounts.google.com;
      worker-src 'self' blob:;
      manifest-src 'self';
    """

    # Permissions Policy (anciennement Feature Policy)
    Permissions-Policy = """
      camera=(self),
      geolocation=(),
      microphone=(),
      payment=(),
      usb=(),
      interest-cohort=()
    """

    # Autres headers de sécurité
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Cache control pour les assets
    Cache-Control = "public, max-age=31536000, immutable"

# Cache spécifique pour le HTML (ne pas cacher)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache pour le service worker (courte durée)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

# Redirections
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Variables d'environnement de build
[context.production.environment]
  NODE_VERSION = "20"

[context.deploy-preview.environment]
  NODE_VERSION = "20"
